-- 순서 무작위로 조회해오기
SELECT
	C.CONTENTID, A.AREACODE, A.READCOUNT, B.NAME AREANAME, C.FIRSTIMAGE, C.TITLE
FROM
  	(SELECT AREACODE, MAX(READCOUNT) READCOUNT FROM YJ_PLACE GROUP BY AREACODE) A,
  	(SELECT AREACODE, NAME FROM YJ_AREACODE WHERE SIGUNGUCODE IS NULL) B,
  	YJ_PLACE C
WHERE
	A.AREACODE = B.AREACODE
  	AND A.READCOUNT = C.READCOUNT
ORDER BY DBMS_RANDOM.RANDOM;

SELECT 
	ROW_NUMBER() OVER (ORDER BY READCOUNT DESC), ADDR1, READCOUNT FROM YJ_PLACE
WHERE AREACODE = 1
	AND ROWNUM <= 2
UNION
SELECT
	ROW_NUMBER() OVER (ORDER BY READCOUNT DESC), ADDR1, READCOUNT FROM YJ_PLACE
WHERE AREACODE = 2
	AND ROWNUM <= 2;